### PR TITLE
Feature: Namespace refactor to `RubyStatistics`

### PR DESCRIPTION
**Pull request by jasoncaryallen**
This PR:
- updates paths throughout the gem from `statistics/` to `ruby-statistics`
- updates namespace throughout the gem from `Statistics` to `RubyStatistics`
- Semantic Version bump to `4.0.0` as it is a breaking namespace change for apps already using `ruby-statistics` gem

Great work on this gem! I hope this contribution helps!
Closes Issue #10

### CODE REVIEW

**Comment by jasoncaryallen** [comment]
> Hola! 👋 thank you so much for your contribution! Highly appreciated !
> 
> I'll take a proper look today and hopefully get it merged with a new version released.

I think I forgot a few updates in the README, but otherwise it should be functionally correct and working in the new namespace. Will have another commit shortly. Cheers!

**Review by estebanz01 — COMMENTED** [review]
I did a review and it good really good! Thank you so much for investing some time on this. It was a pet-peeve of mine for a while 😅 .

I'm going to hold the merge of this PR until #115 & #122 are merged, yeah?

Feel free to review #122 too!

**Review by estebanz01 — APPROVED** [review]
Alright! I'm going to merge this soon.

**Comment by estebanz01** [comment]
@jasoncaryallen if you have time, can you rebase your branch with latest master? it should solve the conflicts that I caused myself by merging a PR that I had to revert 😬

**Comment by jasoncaryallen** [comment]
> @jasoncaryallen if you have time, can you rebase your branch with latest master? it should solve the conflicts that I caused myself by merging a PR that I had to revert 😬

Can do. I’ll try to get to it this evening if possible!

**Comment by jasoncaryallen** [comment]
@estebanz01 - Namespace refactor should be good to go now. Rebased off the main branch and specs are all passing locally and on CI. Please ping me if any additional work is required, or ship it! 🚀  Thanks for maintaining this gem ❤️

**Review by estebanz01 — APPROVED** [review]

**Pull request merged**
